### ISSUE TITLE
STUN: Pending task is being destroyed

### ISSUE THREAD

**Issue by micheljung** [FAForever/server#106]
```
DEBUG:server.lobbyconnection.LobbyConnection:>>: {'target': 'connectivity', 'command': 'SendNatPacket', 'args': ['46.126.105.89:1024', 'Hello from 21447']}
DEBUG:server.connectivity.Connectivity:<server.connectivity.Connectivity object at 0x7f6b001d59e8> sending NAT packet 1 to 46.126.105.89:1025
DEBUG:server.lobbyconnection.LobbyConnection:>>: {'target': 'connectivity', 'command': 'SendNatPacket', 'args': ['46.126.105.89:1025', 'Hello from 21447']}
DEBUG:server.connectivity.Connectivity:<server.connectivity.Connectivity object at 0x7f6b001d59e8> sending NAT packet 2 to 46.126.105.89:1026
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/logging/__init__.py", line 984, in emit
    self.flush()
  File "/usr/local/lib/python3.5/logging/__init__.py", line 964, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'>
Call stack:
  File "./server.py", line 77, in <module>
    loop.run_until_complete(done)
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 330, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 301, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 1198, in _run_once
    handle._run()
  File "/usr/local/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "/code/server/connectivity.py", line 112, in ProbePeerNAT
    self._logger.debug("{} sending NAT packet {} to {}:{}".format(self, i, ip, port))
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1267, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1415, in _log
    self.handle(record)
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1425, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.5/logging/__init__.py", line 855, in handle
    self.emit(record)
  File "/usr/local/lib/python3.5/logging/__init__.py", line 984, in emit
    self.flush()
  File "/usr/local/lib/python3.5/logging/__init__.py", line 964, in flush
    self.stream.flush()
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 92, in __del__
    self._loop.call_exception_handler(context)
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 1057, in call_exception_handler
    self.default_exception_handler(context)
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 1034, in default_exception_handler
    logger.error('\n'.join(log_lines), exc_info=exc_info)
Message: 'Task was destroyed but it is pending!\ntask: <Task pending coro=<GameConnection._handle_lobby_state() done, defined at /code/server/gameconnection.py:143> wait_for=<Future pending cb=[Task._wakeup()
]>>'
Arguments: ()
DEBUG:server.lobbyconnection.LobbyConnection:>>: {'target': 'connectivity', 'command': 'SendNatPacket', 'args': ['46.126.105.89:1026', 'Hello from 21447']}
DEBUG:server.connectivity.Connectivity:<server.connectivity.Connectivity object at 0x7f6b001d59e8> sending NAT packet 3 to 46.126.105.89:1027
DEBUG:server.lobbyconnection.LobbyConnection:>>: {'target': 'connectivity', 'command': 'SendNatPacket', 'args': ['46.126.105.89:1027', 'Hello from 21447']}
```

**Comment by Sheeo** [comment]
Do you have more details on how to reproduce?

**Comment by micheljung** [comment]
No sorry. Let's reopen it when it reoccurs and we have information.
