### ISSUE TITLE
Coop: 'LobbyConnection' object has no attribute 'ip'

### ISSUE THREAD

**Issue by micheljung** [FAForever/server#107]
I observed this multiple times now, alyways in "coop_list"
```
DEBUG:server.lobbyconnection.LobbyConnection:<<: {'command': 'coop_list'}
ERROR:server.lobbyconnection.LobbyConnection:'LobbyConnection' object has no attribute 'ip'
Traceback (most recent call last):
  File "/code/server/lobbyconnection.py", line 134, in on_message_received
    if not self.ensure_authenticated(cmd):
  File "/code/server/lobbyconnection.py", line 120, in ensure_authenticated
    self.abort("Message invalid for unauthenticated connection: %s" % cmd)
  File "/code/server/lobbyconnection.py", line 112, in abort
    self._logger.warning("Aborting %s. %s" % (self.ip, logspam))
AttributeError: 'LobbyConnection' object has no attribute 'ip'
ERROR:server.servercontext.ServerContext:'LobbyConnection' object has no attribute 'ip'
Traceback (most recent call last):
  File "/code/server/lobbyconnection.py", line 134, in on_message_received
    if not self.ensure_authenticated(cmd):
  File "/code/server/lobbyconnection.py", line 120, in ensure_authenticated
    self.abort("Message invalid for unauthenticated connection: %s" % cmd)
  File "/code/server/lobbyconnection.py", line 112, in abort
    self._logger.warning("Aborting %s. %s" % (self.ip, logspam))
AttributeError: 'LobbyConnection' object has no attribute 'ip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/server/servercontext.py", line 71, in client_connected
    await connection.on_message_received(message)
  File "/code/server/lobbyconnection.py", line 171, in on_message_received
    self.abort("Error processing command")
  File "/code/server/lobbyconnection.py", line 112, in abort
    self._logger.warning("Aborting %s. %s" % (self.ip, logspam))
AttributeError: 'LobbyConnection' object has no attribute 'ip'
```

**Comment by Sheeo** [comment]
Fixed in develop branch.
