### ISSUE TITLE
Rating not properly updated (ValueError: Need multiple rating groups)

### ISSUE THREAD

**Issue by micheljung** [FAForever/server#230]
```
2016-10-13 01:57:31.891
GameConnection(Player(Player(Hyross, 190317, (1500.0, 500.0), (1500.0, 500.0))),Game(Game(5268975,Amanite,maps/scmp_009.zip,4))).abort()
2016-10-13 01:57:31.891
ValueError: Need multiple rating groups
2016-10-13 01:57:31.891
raise ValueError('Need multiple rating groups')
2016-10-13 01:57:31.891
File "/usr/local/lib/python3.5/site-packages/trueskill/__init__.py", line 266, in validate_rating_groups
2016-10-13 01:57:31.891
rating_groups, keys = self.validate_rating_groups(rating_groups)
2016-10-13 01:57:31.891
File "/usr/local/lib/python3.5/site-packages/trueskill/__init__.py", line 477, in rate
2016-10-13 01:57:31.891
return global_env().rate(rating_groups, ranks, weights, min_delta)
2016-10-13 01:57:31.891
File "/usr/local/lib/python3.5/site-packages/trueskill/__init__.py", line 700, in rate
2016-10-13 01:57:31.891
return trueskill.rate(rating_groups, ranks)
2016-10-13 01:57:31.891
File "/code/server/games/game.py", line 698, in compute_rating
2016-10-13 01:57:31.891
new_ratings = self.compute_rating(rating='global')
2016-10-13 01:57:31.891
File "/code/server/games/custom_game.py", line 17, in rate_game
2016-10-13 01:57:31.891
await self.rate_game()
2016-10-13 01:57:31.891
File "/code/server/games/game.py", line 340, in on_game_end
2016-10-13 01:57:31.891
Traceback (most recent call last):
2016-10-13 01:57:31.891
Error during game end: Need multiple rating groups
2016-10-13 01:57:31.891
Ranks: [-30]
2016-10-13 01:57:31.891
Rating groups: [{Player(Slauce, 128112, (841.415, 149.605), (1500.0, 500.0)): trueskill.Rating(mu=841.415, sigma=149.605), Player(Keishiro, 152844, (1006.71, 332.455), (1500.0, 500.0)): trueskill.Rating(mu=1006.710, sigma=332.455), Player(Hyross, 190317, (1500.0, 500.0), (1500.0, 500.0)): trueskill.Rating(mu=1500.000, sigma=500.000), Player(Amanite, 64575, (912.433, 105.157), (651.019, 277.562)): trueskill.Rating(mu=912.433, sigma=105.157)}]
```

**Comment by Crotalus** [comment]
Custom game with 4 players vs 4 AI, this is a rating validity case we need to test for and not try to rate :)
