### ISSUE TITLE
Player stats sometimes not stored

### ISSUE THREAD

**Issue by micheljung** [FAForever/server#253]
Grothe reported that for game 5476461
> ladder replay only shows up at my replays with only me as player, and wasn't counted.

Indeed the other player (UltraGodzilla1) wasn't even inserted into `game_player_stats`:

```
mysql> select * from game_player_stats where gameid = 5476461;
+----------+---------+----------+----+---------+-------+------+-------+---------+-----------+------------+-----------------+-------+-----------+
| id       | gameId  | playerId | AI | faction | color | team | place | mean    | deviation | after_mean | after_deviation | score | scoreTime |
+----------+---------+----------+----+---------+-------+------+-------+---------+-----------+------------+-----------------+-------+-----------+
| 10201059 | 5476461 |   112924 |  0 |       1 |     1 |    1 |     1 | 856.997 |   66.2149 |       NULL |            NULL |    -1 | NULL      |
+----------+---------+----------+----+---------+-------+------+-------+---------+-----------+------------+-----------------+-------+-----------+
```

Log statements containing the game ID:
```
 GameConnection(Player(Player(Grothe, 112924, (1094.78, 59.6142), (856.997, 66.2149))),Game(Game(5476461,Grothe,maps/sleipnir.v0007.zip,1))).abort()
 Executing query: UPDATE game_stats SET validity = %s WHERE id = %s with args: (13, 5476461)
 Removed game connection GameConnection(Player(Player(Grothe, 112924, (1094.78, 59.6142), (856.997, 66.2149))),Game(Game(5476461,Grothe,maps/sleipnir.v0007.zip,1)))
 GameConnection(Player(Player(UltraGodzilla1, 83672, (1050.9, 90.7373), (858.0639502538241, 95.31043935730206))),Game(Game(5476461,Grothe,maps/sleipnir.v0007.zip,1))).abort()
 Army stats could not be processed from player Player(Grothe, 112924, (1094.78, 59.6142), (856.997, 66.2149)) in game Game(5476461,Grothe,maps/sleipnir.v0007.zip,1)
 Executing query: bytearray(b"INSERT INTO `game_player_stats` (`gameId`, `playerId`, `faction`, `color`, `team`, `place`, `mean`, `deviation`, `AI`, `score`) VALUES (5476461, \'112924\', 1, 1, 1, 1, 856.997, 66.2149, 0, -1)") with args: None
 Executing query: INSERT INTO game_stats(id, gameType, gameMod, `host`, mapId, gameName, validity)VALUES(%s, %s, %s, %s, %s, %s, %s) with args: (5476461, '0', 6, 112924, 6597, 'Grothe Vs UltraGodzilla1', 0)
 Added game connection GameConnection(Player(Player(Grothe, 112924, (1094.78, 59.6142), (856.997, 66.2149))),Game(Game(5476461,Grothe,maps/sleipnir.v0007.zip,0)))
 <server.connectivity.Connectivity object at 0x7f067b011f28> probing GameConnection(Player(Player(UltraGodzilla1, 83672, (1050.9, 90.7373), (858.0639502538241, 95.31043935730206))),Game(Game(5476461,Grothe,maps/sleipnir.v0007.zip,0))) at Address(host='192.77.143.232', port='39225') with msg: Hello from 112924
 <server.connectivity.Connectivity object at 0x7f067b011f28> probing GameConnection(Player(Player(UltraGodzilla1, 83672, (1050.9, 90.7373), (858.0639502538241, 95.31043935730206))),Game(Game(5476461,Grothe,maps/sleipnir.v0007.zip,0))) at Address(host='192.77.143.232', port=13090) with msg: Hello from 112924
 <server.connectivity.Connectivity object at 0x7f068424c518> probing GameConnection(Player(Player(Grothe, 112924, (1094.78, 59.6142), (856.997, 66.2149))),Game(Game(5476461,Grothe,maps/sleipnir.v0007.zip,0))) at Address(host='91.61.109.116', port=6112) with msg: Hello from 83672
 Connecting GameConnection(Player(Player(UltraGodzilla1, 83672, (1050.9, 90.7373), (858.0639502538241, 95.31043935730206))),Game(Game(5476461,Grothe,maps/sleipnir.v0007.zip,0))) to host GameConnection(Player(Player(Grothe, 112924, (1094.78, 59.6142), (856.997, 66.2149))),Game(Game(5476461,Grothe,maps/sleipnir.v0007.zip,0))) using STUN
 >>: {'uid': 5476461, 'command': 'game_launch', 'args': ['/numgames 49'], 'mapname': 'sleipnir.v0007', 'mod': 'ladder1v1'}
 >>: {'uid': 5476461, 'command': 'game_launch', 'args': ['/numgames 698'], 'mapname': 'sleipnir.v0007', 'mod': 'ladder1v1'}
 Game(5476461,,maps/SCMP_007.zip,0) created
```

As we can see above, " Added game connection" is only called for Grothe.
For the other player, it's probably the following that prevents the game connection from being added:
```
server.games.game.GameError: Invalid GameState: 0
raise GameError("Invalid GameState: {state}".format(state=self.state))
File "/code/server/games/game.py", line 293, in add_game_connection
self.game.add_game_connection(self)
File "/code/server/gameconnection.py", line 132, in _handle_lobby_state
Traceback (most recent call last):
Invalid GameState: 0
```

**Comment by Askaholic** [comment]
Old issue
