### ISSUE TITLE
logging error

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/server#267]
Should be simple to fix.

```
Feb  4 07:52:49 stabler docker/50547186f6cd[859]: --- Logging error ---
Feb  4 07:52:49 stabler docker/50547186f6cd[859]: Traceback (most recent call last):
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:   File "/usr/local/lib/python3.5/logging/__init__.py", line 980, in emit
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:     msg = self.format(record)
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:   File "/usr/local/lib/python3.5/logging/__init__.py", line 830, in format
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:     return fmt.format(record)
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:   File "/usr/local/lib/python3.5/logging/__init__.py", line 567, in format
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:     record.message = record.getMessage()
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:   File "/usr/local/lib/python3.5/logging/__init__.py", line 330, in getMessage
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:     msg = msg % self.args
Feb  4 07:52:49 stabler docker/50547186f6cd[859]: TypeError: %d format: a number is required, not str
Feb  4 07:52:49 stabler docker/50547186f6cd[859]: Call stack:
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:   File "server.py", line 85, in <module>
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:     loop.run_until_complete(done)
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:   File "/usr/local/lib/python3.5/asyncio/base_events.py", line 325, in run_until_complete
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:     self.run_forever()
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:   File "/usr/local/lib/python3.5/asyncio/base_events.py", line 295, in run_forever
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:     self._run_once()
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:   File "/usr/local/lib/python3.5/asyncio/base_events.py", line 1254, in _run_once
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:     handle._run()
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:   File "/usr/local/lib/python3.5/asyncio/events.py", line 125, in _run
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:     self._callback(*self._args)
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:   File "/usr/local/lib/python3.5/asyncio/tasks.py", line 301, in _wakeup
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:     self._step()
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:   File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:     result = coro.send(None)
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:   File "/code/server/servercontext.py", line 69, in client_connected
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:     await connection.on_message_received(message)
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:   File "/code/server/lobbyconnection.py", line 146, in on_message_received
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:     handler(message)
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:   File "/code/server/decorators.py", line 22, in wrapper
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:     result = f(*args, **kwargs)
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:   File "/code/server/lobbyconnection.py", line 882, in command_game_join
Feb  4 07:52:49 stabler docker/50547186f6cd[859]:     self._logger.debug("joining: %d:%d with pw: %s", uuid, port, password)
Feb  4 07:52:49 stabler docker/50547186f6cd[859]: Message: 'joining: %d:%d with pw: %s'
Feb  4 07:52:49 stabler docker/50547186f6cd[859]: Arguments: ('5756489', 6112, None)
```

**Comment by Askaholic** [comment]
Looks like this happened because `uuid` was sent as a string instead of an integer. My guess is this was a client issue (sending something like `{... "uid": "5756489" ... }` instead of `{... "uid": 5756489  ...}`). Still the server code should be able to handle either case. This is as easy as adding `int(message['uid'])`

Currently the error handling code will catch this and kill the connection.
