### ISSUE TITLE
error calculating game result

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/server#268]
```
Feb  4 07:51:57 stabler docker/50547186f6cd[859]: Player(ydinasevaltio, 163442, (908.967, 100.62), (237.158, 175.212)) reported result f
or army 2: defeat -10
Feb  4 07:51:57 stabler docker/50547186f6cd[859]: Processing game stats for player: mf88ki
Feb  4 07:51:57 stabler docker/50547186f6cd[859]: Army stats could not be processed from player Player(mf88ki, 176166, (877.336, 195.52)
, (739.674, 148.23)) in game Game(5756233,AdmiralZero,maps/scmp_009.zip,8)
Feb  4 07:51:57 stabler docker/50547186f6cd[859]: Traceback (most recent call last):
Feb  4 07:51:57 stabler docker/50547186f6cd[859]:   File "/code/server/games/game.py", line 279, in _process_army_stats_for_player
Feb  4 07:51:57 stabler docker/50547186f6cd[859]:     await self._game_stats_service.process_game_stats(player, self, self._army_stats)
Feb  4 07:51:57 stabler docker/50547186f6cd[859]:   File "/code/server/stats/game_stats_service.py", line 56, in process_game_stats
Feb  4 07:51:57 stabler docker/50547186f6cd[859]:     survived = army_result[1] == 'victory'
Feb  4 07:51:57 stabler docker/50547186f6cd[859]: IndexError: list index out of range
```

**Comment by micheljung** [comment]
See #262

**Comment by duk3luk3** [comment]
ah cool. I'll close this then.
