### ISSUE TITLE
First ladder match fails to start

### ISSUE THREAD

**Issue by Askaholic** [FAForever/server#401]
First match has game state issue. Matches after that seem to launch correctly.

```
DEBUG    server.gameconnection.GameConnection GameConnection initializing
DEBUG    server.lobbyconnection.LobbyConnection >>: {'command': 'game_launch', 'mod': 'ladder1v1', 'uid': 8571514, 'args': ['/numgames 648'], 'mapname': 'scmp_026'}
INFO     server.lobbyconnection.LobbyConnection Player(Yewor, 139665, (1342.48, 96.716), (100.0, 1.0)) stopped searching for ladder: Search(Player(Yewor, 139665, (1342.48, 96.716), (100.0, 1.0)), 0.55, 0.25)
DEBUG    server.gameconnection.GameConnection Connecting GameConnection(Player(Yewor, 139665, (1342.48, 96.716), (100.0, 1.0)), Game(8571514,Gardelouve,maps/scmp_026.zip,0)) to host GameConnection(Player(Gardelouve, 161739, (1300.24, 90.8998), (19.7385, 10.047)), Game(8571514,Gardelouve,maps/scmp_026.zip,0)) directly
DEBUG    server.lobbyconnection.LobbyConnection >>: {'command': 'JoinGame', 'args': [Address(host='81.254.196.23', port=6112), 'Gardelouve', 161739], 'target': 'game'}
DEBUG    server.lobbyconnection.LobbyConnection >>: {'command': 'ConnectToPeer', 'args': [Address(host='2.24.178.153', port=6112), 'Yewor', 139665], 'target': 'game'}
ERROR    server.gameconnection.GameConnection Invalid GameState: 0
Traceback (most recent call last):
  File "/code/server/gameconnection.py", line 137, in _handle_lobby_state
    self.game.add_game_connection(self)
  File "/code/server/games/game.py", line 335, in add_game_connection
    raise GameError("Invalid GameState: {state}".format(state=self.state))
server.games.game.GameError: Invalid GameState: 0
INFO     LadderGame.8571514             Added game connection GameConnection(Player(Gardelouve, 161739, (1300.24, 90.8998), (19.7385, 10.047)), Game(8571514,Gardelouve,maps/scmp_026.zip,0))
DEBUG    server.lobbyconnection.LobbyConnection >>: {'command': 'HostGame', 'args': ['scmp_026'], 'target': 'game'}
```

**Comment by Askaholic** [comment]
Fixed by #426
