### ISSUE TITLE
500 Internal Server Error when trying to upload a map to the Map Vault

### ISSUE THREAD

**Issue by Wizek** [FAForever/server#483]
Details: 

https://www.screencast.com/t/wig6l7xEO6

```
Map could not be uploaded. Server gave the following errors: 500 Internal Server Error

org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 Internal Server Error
  at org.springframework.web.client.HttpServerErrorException.create(HttpServerErrorException.java:79)
  at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:99)
  at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:79)
  at com.faforever.client.api.JsonApiErrorHandler.handleError(JsonApiErrorHandler.java:31)
  at org.springframework.security.oauth2.client.http.OAuth2ErrorHandler.handleError(OAuth2ErrorHandler.java:84)
  at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
  at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:777)
  at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:735)
  at org.springframework.security.oauth2.client.OAuth2RestTemplate.doExecute(OAuth2RestTemplate.java:128)
  at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:669)
  at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:444)
  at com.faforever.client.api.FafApiAccessorImpl.post(FafApiAccessorImpl.java:544)
  at com.faforever.client.api.FafApiAccessorImpl.uploadMap(FafApiAccessorImpl.java:290)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  at java.base/java.lang.reflect.Method.invoke(Unknown Source)
  at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
  at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:206)
  at com.sun.proxy.$Proxy67.uploadMap(Unknown Source)
  at com.faforever.client.map.MapUploadTask.call(MapUploadTask.java:86)
  at com.faforever.client.map.MapUploadTask.call(MapUploadTask.java:30)
  at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
  at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  at java.base/java.lang.Thread.run(Unknown Source)
```

Link to the map in question: https://drive.google.com/open?id=1iulQ-rRvL6vi0Q7PRzdDWEgrCky2korg

**Comment by Wizek** [comment]
I just found out that FAFMapEditor v0.605 also has an upload function, so gave it a try. It also returned a 500 server error, however this time with more details:

https://www.screencast.com/t/h8whXOoIiJW

For some reason the server thinks that my map has a zip bomb in it. Which is strange since the zip was created both by FAFMapEditor and DownlordsFAFClient themselves just before upload. What gives? Likely a false positive, right? Could I somehow sidestep this issue and upload?

Also, someone else seems to be having the same issue here: https://discord.gg/Z5pVWSx in the #faf&#xfeff;-&#xfeff;editor channel.

**Comment by Askaholic** [comment]
This is an API issue not lobby server. @Brutus5000 can you transfer?

**Comment by Wizek** [comment]
I've moved it [over here](https://github.com/FAForever/faf-java-api/issues/326) @Askaholic. That is the right place, right? Either way, thanks for the heads up!
