### ISSUE TITLE
MySQL syntax error in GameConnection.handle_game_mods

### ISSUE THREAD

**Issue by Askaholic** [FAForever/server#657]
The error:
```
ERROR    Sep 03  12:53:59 GameConnection                 Something awful happened in a game thread!
Traceback (most recent call last):
  File "/code/server/gameconnection.py", line 204, in handle_action
    await COMMAND_HANDLERS[command](self, *args)
  File "/code/server/gameconnection.py", line 259, in handle_game_mods
    ids=tuple(uids))
  File "/code/src/aiomysql/aiomysql/sa/connection.py", line 173, in _execute
    await cursor.execute(str(compiled), post_processed_params)
  File "/code/src/aiomysql/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/code/src/aiomysql/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/code/src/aiomysql/aiomysql/connection.py", line 428, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/code/src/aiomysql/aiomysql/connection.py", line 622, in _read_query_result
    await result.read()
  File "/code/src/aiomysql/aiomysql/connection.py", line 1105, in read
    first_packet = await self.connection._read_packet()
  File "/code/src/aiomysql/aiomysql/connection.py", line 593, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1")
```

The source code:
https://github.com/FAForever/server/blob/ccf349e3b4bbaee95373d79a0e2f4ee9c5d064a2/server/gameconnection.py#L256-L259

**Comment by Askaholic** [comment]
We should probably rewrite this query using sqlalchemy's `in_` method. See https://stackoverflow.com/a/20079833
