### ISSUE TITLE
Refactor tests to close protocol connections automatically

### ISSUE THREAD

**Issue by Askaholic** [FAForever/server#717]
In the `tests/integration_tests`, if protocols are not closed at the end of a test you might see an exception like this:
```
Exception ignored in: <coroutine object ServerContext.client_connected at 0x7f9a9c6295f0>
Traceback (most recent call last):
  File "/home/dope/Documents/fa-server/server/servercontext.py", line 92, in client_connected
    message = await protocol.read_message()
  File "/home/dope/Documents/fa-server/server/protocol/protocol.py", line 122, in close
    self.writer.close()
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 317, in close
    return self._transport.close()
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 663, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 691, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

This can be prevented by calling `await proto.close()` at the end of the test. However, we should refactor protocol creation to use a fixture which does this automatically when the test ends.

**Comment by Askaholic** [comment]
Fixed in #728
