### ISSUE TITLE
Non-ascii clan name can cause tmm match to fail

### ISSUE THREAD

**Issue by Askaholic** [FAForever/server#721]
If both players on a team are members of a clan with non-ascii characters in the clan tag, then the game name that gets created will contain non-ascii characters and will be rejected, causing the match to be cancelled.

```
INFO     Feb 18  21:03:23 Search                         Matched Search(tmm_2v2, [Player(Shinobu, 44898, (2231.63, 96.4996)), Player(FtXCommando, 62213, (2022.73, 121.69))], threshold=0.68, expansion=0.05) with Search(tmm_2v2, [Player(TURBO2, 89695, (2353.8778029868736, 109.35106982969995)), Player(Espeperant, 189718, (2116.247376374932, 88.8876522634832))], threshold=0.74, expansion=0.0)
INFO     Feb 18  21:03:23 Search                         Matched Search(tmm_2v2, [Player(TURBO2, 89695, (2353.8778029868736, 109.35106982969995)), Player(Espeperant, 189718, (2116.247376374932, 88.8876522634832))], threshold=0.74, expansion=0.0) with Search(tmm_2v2, [Player(Shinobu, 44898, (2231.63, 96.4996)), Player(FtXCommando, 62213, (2022.73, 121.69))], threshold=0.68, expansion=0.05)
INFO     Feb 18  21:03:23 PopTimer                       Next tmm2v2 wave happening in 179s
ERROR    Feb 18  21:03:23 LadderService                  Failed to start ladder game!
Traceback (most recent call last):
  File "/code/server/ladder_service.py", line 379, in start_game
    max_players=len(all_players)
  File "/code/server/game_service.py", line 166, in create_game
    game = game_class(**game_args)
  File "/code/server/games/ladder_game.py", line 28, in __init__
    super().__init__(id_, *args, **new_kwargs)
  File "/code/server/games/game.py", line 84, in __init__
    self.name = name
  File "/code/server/games/game.py", line 141, in name
    raise ValueError("Name must be ascii!")
ValueError: Name must be ascii!
```

Ftx and Shinobu are both in a clan with the tag `J¢p`.

I think the choices are:
1. Allow a bypass to the ascii check for internal use.
2. Only use clan tag if the clan tag is ascii
3. Remove the ascii check entirely

I think option 1 actually does make sense. If we're already allowing those characters in the clan tag, there's no harm in allowing them in the game name. The ascii enforcement is mostly there to prevent custom lobbies having names in weird encodings that don't render properly on other systems.

**Comment by Brutus5000** [comment]
I agree, #1 sounds like a valid solution.
