### ISSUE TITLE
Players in queue with IDLE state

### ISSUE THREAD

**Issue by Askaholic** [FAForever/server#752]
Here's an example where player `Iruma-Kun` matches, disconnects from the game before it can launch, and queues again which leaves them in an `IDLE` state instead of `SEARCHING_LADDER` subsequently failing any further attempts to match them until some time later.

```
INFO     Mar 29  16:09:53 LadderService                  Search(ladder_1v1, [Player(Iruma-Kun, 335089, (651.453, 65.8918))], threshold=0.77, expansion=0.0) started searching for ladder1v1
INFO     Mar 29  16:11:46 Search                         Matched Search(ladder_1v1, [Player(Iruma-Kun, 335089, (651.453, 65.8918))], threshold=0.77, expansion=0.0) with Search(ladder_1v1, [Player(MasterFantaster, 156042, (851.8952346327048, 65.20526221423584))], threshold=0.77, expansion=0.0)
INFO     Mar 29  16:11:46 Search                         Matched Search(ladder_1v1, [Player(MasterFantaster, 156042, (851.8952346327048, 65.20526221423584))], threshold=0.77, expansion=0.0) with Search(ladder_1v1, [Player(Iruma-Kun, 335089, (651.453, 65.8918))], threshold=0.77, expansion=0.0)
INFO     Mar 29  16:11:57 LadderGame.14183193            Added game connection GameConnection(Player(Iruma-Kun, 335089, (1500.0, 500.0), (651.453, 65.8918)), Game(14183193, Iruma-Kun, maps/scmp_007.zip))
INFO     Mar 29  16:12:20 LadderGame.14183193            Added game connection GameConnection(Player(MasterFantaster, 156042, (960.751, 9      7.8293), (851.8952346327048, 65.20526221423584)), Game(14183193, Iruma-Kun, maps/scmp_007.zip))
INFO     Mar 29  16:12:26 LadderGame.14183193            Removed game connection GameConnection(Player(Iruma-Kun, 335089, (1500.0, 500.0), (651.453, 65.8918)), Game(14183193, Iruma-Kun, maps/scmp_007.zip))
INFO     Mar 29  16:12:26 LadderGame.14183193            Game cancelled pre launch
INFO     Mar 29  16:12:43 LadderService                  Search(ladder_1v1, [Player(Iruma-Kun, 335089, (651.453, 65.8918))], threshold=0.77, expansion=0.0) started searching for ladder1v1
ERROR    Mar 29  16:13:07 LadderService                  Failed to start ladder game! 
Traceback (most recent call last):
  File "/code/server/ladder_service.py", line 469, in start_game
    await game.wait_launched(60 + 10 * len(all_guests))
  File "/code/server/games/game.py", line 273, in wait_launched
    timeout=timeout
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
WARNING  Mar 29  16:14:46 MatchmakerQueue                Tried to match searches Search(ladder_1v1, [Player(perekup, 117903, (518.203, 66.1051))], threshold=0.77, expansion=0.0) and Search(ladder_1v1, [Player(Iruma-Kun, 335089, (651.453, 65.8918))], threshold=0.77, expansion=0.0) while some players had invalid states: team1: [<PlayerState.SEARCHING_LADDER: 5>] team2: [<PlayerState.IDLE: 1>]
WARNING  Mar 29  16:17:46 MatchmakerQueue                Tried to match searches Search(ladder_1v1, [Player(Iruma-Kun, 335089, (651.453, 65.8918))], threshold=0.77, expansion=0.0) and Search(ladder_1v1, [Player(perekup, 117903, (518.203, 66.1051))], threshold=0.77, expansion=0.0) while some players had invalid states: team1: [<PlayerState.IDLE: 1>] team2: [<PlayerState.SEARCHING_LADDER: 5>]
INFO     Mar 29  16:18:18 LadderGame.14183193            Removed game connection GameConnection(Player(MasterFantaster, 156042, (960.751,       97.8293), (851.8952346327048, 65.20526221423584)), Game(14183193, Iruma-Kun, maps/scmp_007.zip))
WARNING  Mar 29  16:20:47 MatchmakerQueue                Tried to match searches Search(ladder_1v1, [Player(Iruma-Kun, 335089, (651.453, 65.8918))], threshold=0.77, expansion=0.0) and Search(ladder_1v1, [Player(perekup, 117903, (518.203, 66.1051))], threshold=0.77, expansion=0.0) while some players had invalid states: team1: [<PlayerState.IDLE: 1>] team2: [<PlayerState.SEARCHING_LADDER: 5>]
INFO     Mar 29  16:22:31 LadderService                  Search(ladder_1v1, [Player(Iruma-Kun, 335089, (651.453, 65.8918))], threshold=0.77, expansion=0.0) stopped searching for ladder1v1
INFO     Mar 29  16:26:53 LadderService                  Search(ladder_1v1, [Player(Iruma-Kun, 335089, (651.453, 65.8918))], threshold=0.77, expansion=0.0) started searching for ladder1v1
INFO     Mar 29  16:29:46 Search                         Matched Search(ladder_1v1, [Player(Arusardy, 302961, (620.7365603936462, 67.35423604326401))], threshold=0.72, expansion=0.05) with Search(ladder_1v1, [Player(Iruma-Kun, 335089, (651.453, 65.8918))], threshold=0.77, expansion=0.0)
INFO     Mar 29  16:29:46 Search                         Matched Search(ladder_1v1, [Player(Iruma-Kun, 335089, (651.453, 65.8918))], threshold=0.77, expansion=0.0) with Search(ladder_1v1, [Player(Arusardy, 302961, (620.7365603936462, 67.35423604326401))], threshold=0.72, expansion=0.05)
```

**Comment by Askaholic** [comment]
Ok, I think it happens because the cleanup code in `LaddeService.start_game` unconditionally sets the players states to IDLE. It would probably be best if `LadderService` did not modify the state here, and instead called `abort` on any existing game connection objects. This would handle setting state to IDLE for any players who are still connected. Players who have already disconnected would be unaffected then.
